---
allow_duplicates: no

galaxy_info:
  author: Ryan Olson
  description: Install Singularity
  license: 3-clause BSD license.
  min_ansible_version: 1.6
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
  galaxy_tags:
    - ubuntu 
    - containers
  dependencies: []

